// // 20230902194606
// // http://localhost:9999/api/v1/products

// {
//     "data": [
//       {
//         "_id": "64f0208a1e3a647be4234cdf",
//         "Model": "Xtreme RIO 2:1 Multimedia Speaker",
//         "InputSensitivity": "3.5ST/USB/SD",
//         "FrequencyResponse": "Sat: 120Hz-20KHz,\nSub: >20Hz-170Hz",
//         "Price": 3075,
//         "Brand": "XTREME",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "The Xtreme RIO 2:1 Multimedia Speaker features an output power of 15W + 10Wx2 (35 RMS). It requires a power supply of ~230V 50Hz. This multimedia speaker has been equipped with Sat: 3″ x 2 + Sub: 5″ driver units. The Satellite has a frequency response of 120Hz-20KHz and the subwoofer has a frequency response of about >20Hz-170Hz. It has a separation of >40dB and sound to noise ratio of about >70dB. It features distortion of <0.5% (1K, 1W). The dimension of the subwoofer is 150 x 240 x 268 mm and the size of the satellite is 95 x 157 x 89 mm.",
//         "Category": "Speaker",
//         "ProductId": 4019,
//         "img1": "https://i.ibb.co/x35Np2y/Xtreme-RIO-2-1-Multimedia-Speaker-1.png",
//         "img2": "https://i.ibb.co/QFFC5Lb/Xtreme-RIO-2-1-Multimedia-Speaker-2.png",
//         "AvgRatings": 3.6,
//         "Status": "Out of Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd7",
//         "Model": "Microlab M-105R 2.1 multimedia speaker",
//         "InputSensitivity": "40 Hz – 20 kHz",
//         "FrequencyResponse": "40 Hz – 20 kHz",
//         "Price": 1700,
//         "Brand": "Microlab",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Mini classic 2.1 multimedia speaker with remote cotrol for convenient use. Small wooden cabinets produce crystal clear sound. It allows you to enjoy full range music playbacks.\n\n2.1 speaker system in a mini vintage style,Wooden cabinets for perfect acoustic performance and crystal clear music experience, Bass reflex tunnel on frontal panel for deeper bass.Woofer driver outside the bottom of subwoofer cabinet.",
//         "Category": "Speaker",
//         "ProductId": 4011,
//         "img1": "https://i.ibb.co/XD68KwX/Microlab-M-105-R-2-1-multimedia-speaker-1.png",
//         "img2": "https://i.ibb.co/YD7kJtj/Microlab-M-105-R-2-1-multimedia-speaker-2.png",
//         "AvgRatings": 3.1,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd1",
//         "Model": "Edifier M201BT Bluetooth Speaker",
//         "InputSensitivity": "AUX Input R/L: 500±500mV SW: 110±20mV",
//         "FrequencyResponse": "R/L: 210Hz-20KHz SW: 63Hz-206Hz",
//         "Price": 5500,
//         "Brand": "Edifier",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Adopt digital audio processing, precise electronic frequency division and dynamic management, well match the characteristics of the unit, and ensure the balance of middle and high frequency. Equipped with a 131mm large-diameter woofer, combined with a front-mounted inverter tube, the low frequency is powerful and powerful, and the sound field atmosphere is panoramically constructed.",
//         "Category": "Speaker",
//         "ProductId": 4005,
//         "img1": "https://i.ibb.co/FgtS9fm/Edifier-M201-BT-Bluetooth-Speaker-1.png",
//         "img2": "https://i.ibb.co/2YNcrfw/Edifier-M201-BT-Bluetooth-Speaker-2.png",
//         "AvgRatings": 3.1,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cdd",
//         "Model": "XTREME E278BU 2:1 Multimedia Speaker",
//         "InputSensitivity": "3.5ST/USB/SD",
//         "FrequencyResponse": "120Hz-20KHz",
//         "Price": 2500,
//         "Brand": "XTREME",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Xtreme E278BU is the quality 2.1 speaker comes from Microlab M series. It will bring full audio range music to your life. Beautiful finish design E278BU has the stylish black colors design, which is super beautiful for your personal space decoration and display. The wooden materials can also be kept for a long period.Great sound solution E278BU provides clean and detailed quality sound for most of your music needs. It is ideal for watching movies, playing games and listening to high definition music.Easy music control E278BU provides convenient control solution to every music lovers. It features the front volume control for quick sound adjustment.Xtreme-developed robust bass replay technology, based on the design of woofer unit and geometric structure of subwoofer cabinet.",
//         "Category": "Speaker",
//         "ProductId": 4017,
//         "img1": "https://i.ibb.co/MnSCYyQ/XTREME-E278-BU-2-1-Multimedia-Speaker-1.png",
//         "img2": "https://i.ibb.co/Fb1hymt/XTREME-E278-BU-2-1-Multimedia-Speaker-2.png",
//         "AvgRatings": 3.4,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd9",
//         "Model": "Microlab M-108 Multimedia 2.1 Speaker",
//         "InputSensitivity": "3.5mm stereo jack",
//         "FrequencyResponse": "40 Hz – 18 kHz",
//         "Price": 2500,
//         "Brand": "Microlab",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Quality 2.1 speaker system with built-in amplifier 11 Watt of acoustic power with 4″ woofer and 2 x 3″ satellite Full audio spectrum performances, ideal for your favorite entertainment from Mp3, Mp4, CD/DVD movies and digital playbacks Specially designed woofer cabinet with bass reflex tunnel for deep bass Front panel volume control for quick access Angled satellites for optimum listening and with stands for firm support",
//         "Category": "Speaker",
//         "ProductId": 4013,
//         "img1": "https://i.ibb.co/jhLwC0m/Microlab-M-108-Multimedia-2-1-Speaker-1.png",
//         "img2": "https://i.ibb.co/nCc1zYp/Microlab-M-108-Multimedia-2-1-Speaker-2.png",
//         "AvgRatings": 3.3,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd5",
//         "Model": "Fantech GS301 Trifecta RGB Bluetooth Gaming Speaker",
//         "InputSensitivity": "3.5mm+USB",
//         "FrequencyResponse": "20Hz-16KHz",
//         "Price": 2600,
//         "Brand": "Fantech",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Fantech GS301 Trifecta RGB Bluetooth Gaming Speaker comes with 3.5mm & USB Input interface. This gaming speaker featured with Driver unit: 45mm, Speaker sensitivity: 90dB, Frequency response: 20Hz-16KHz, Total harmonic distortion: <5%, Impedance: 4, Bluetooth version: 5.0, Spectrum mode: 6, Output power: 5W x 2 and Working temperature: -40C to 85C. This Fantech GS301 Trifecta Gaming Speaker is designed with RGB lights that enhance your music and gaming experience. You can easily control its power and volume by adjusting the knob. In this speaker, for its bigger output power, each driver produces higher sound pressure to pump out bigger and more empowering sound. The latest Fantech GS301 Trifecta RGB Bluetooth Gaming",
//         "Category": "Speaker",
//         "ProductId": 4009,
//         "img1": "https://i.ibb.co/kh3Kwpp/Fantech-GS301-Trifecta-RGB-Bluetooth-Gaming-Speaker-1.png",
//         "img2": "https://i.ibb.co/vcBMbMR/Fantech-GS301-Trifecta-RGB-Bluetooth-Gaming-Speaker-2.png",
//         "AvgRatings": 3,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234ce0",
//         "Model": "MaxGreen MG-SILVER-650VA 650VA Offline UPS",
//         "Capacity": "650VA",
//         "Input": "140-290VAC",
//         "Output": "220/230 V",
//         "Brand": "MaxGreen",
//         "BackupTime": "15-20 minutes (Depends on load)",
//         "Price": 3199,
//         "Details": "The MaxGreen MG-SILVER-650VA Offline UPS comes with 220/230 V Input Voltage, 140-290VAC Input Voltage Range, 50 Hz Frequency. It has a Output Voltage of 220/230 V. This offline UPS also features Â±10% (Bat Mode) AC voltage regulation. It has a backup time of 15-20 minutes (Depends on load). The MaxGreen MG-SILVER-650VA Offline UPS also has Simulated Sine Wave. It has a 1x 7 Ah Internal maintenance-free lead-acid battery. The MaxGreen MG-SILVER-650VA Offline UPS comes with 01 year warranty.",
//         "Category": "UPS",
//         "ProductId": 801,
//         "img1": "https://i.ibb.co/PMdwQ1D/Max-Green-MG-SILVER-650-VA-650-VA-Offline-UPS-1.png",
//         "img2": "https://i.ibb.co/Vq67Z7r/Max-Green-MG-SILVER-650-VA-650-VA-Offline-UPS-2.png",
//         "Status": "In Stock",
//         "AvgRatings": 4.6,
//         "Reviews": [
//           "The UPS I selected has provided reliable backup power during outages, ensuring the safety of my devices. However, it could have a more intuitive control interface.",
//           "I'm quite satisfied with my UPS's performance, as it offers ample runtime and surge protection. Still, it's relatively heavy and may require sturdy placement.",
//           "My selected UPS has proven itself to be a dependable choice, safeguarding my electronics during power fluctuations. However, it may not be the most energy-efficient option.",
//           "The UPS has performed well, offering peace of mind during power interruptions. However, it could have more accessible battery replacement options."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cce",
//         "Model": "Edifier R103V 2:1 Multimedia Speaker",
//         "InputSensitivity": "R/L：350±50mV SW：200±50mV",
//         "FrequencyResponse": "70Hz~20KHz",
//         "Price": 2200,
//         "Brand": "Edifier",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Edifier R103V 2:1 Multimedia Speaker is a very attractive dual magnetic circuit design 2:1 multimedia speaker. Its 4-inch attractively shielded and wooden chambered subwoofer provides perfect bass. This audio device required RMS 2-watt x 2 + 4.5-watt total power output to generate smooth sound with the help of side-mounted bass reflection. This 3kg of total weight elegant speaker has a 3.5mm stereo input and a green LED power indicator to make it user-friendly. Find the best 2:1 desktop speaker at a reasonable price in Rangpur, Dhaka, Chittagong & Sylhet.",
//         "Category": "Speaker",
//         "ProductId": 4002,
//         "img1": "https://i.ibb.co/9YN4Nvm/Edifier-R103-V-2-1-Multimedia-Speaker-1.png",
//         "img2": "https://i.ibb.co/sJ55HRY/Edifier-R103-V-2-1-Multimedia-Speaker-2.png",
//         "AvgRatings": 4.5,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd8",
//         "Model": "Microlab M100U 2.1 Multimedia Speaker",
//         "InputSensitivity": "3.5mm stereo jack",
//         "FrequencyResponse": "35 Hz – 20 kHz",
//         "Price": 2100,
//         "Brand": "Microlab",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Great sound solution for most of your needs, this 2.1 speaker system brings full audio range to your playback media. Featuring woofer cabinet and compact satellites for clearer highs. Ideal for multimedia entertainment use in study room, bedroom or kitchen.\nBuilt with quality drivers for enhancing your movies and music entertainment with better sound and effects. Front panel controls for media playback and interfaces for playing your digital music.",
//         "Category": "Speaker",
//         "ProductId": 4012,
//         "img1": "https://i.ibb.co/0DwytZB/Microlab-M100-U-2-1-Multimedia-Speaker-1.png",
//         "img2": "https://i.ibb.co/TMjWb28/Microlab-M100-U-2-1-Multimedia-Speaker-2.png",
//         "AvgRatings": 4.7,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd2",
//         "Model": "Fantech Sonar GS202 Hi-res Audio Gaming Speaker",
//         "InputSensitivity": "USB& 3.5mm plug",
//         "FrequencyResponse": "150 Hz- 20kHz (±5db)",
//         "Price": 975,
//         "Brand": "Fantech",
//         "Type": "Wired",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Clear, Deep, and Perfect Sound 360° surround sound Hi-res audio 45mm driver unit Lighting effects Magnet free material body Multi-platform compatibility (Laptop, Desktop, Cellphone) USB& 3.5mm plug Dimensions: 100mm*80mm",
//         "Category": "Speaker",
//         "ProductId": 4006,
//         "img1": "https://i.ibb.co/qCMn82M/Fantech-Sonar-GS202-Hi-res-Audio-Gaming-Speaker-1.png",
//         "img2": "https://i.ibb.co/6Jnr5Ff/Fantech-Sonar-GS202-Hi-res-Audio-Gaming-Speaker-2.png",
//         "AvgRatings": 3.7,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cdc",
//         "Model": "XTREME HERO 2.1 SPEAKER",
//         "InputSensitivity": "3.5ST/USB/SD",
//         "FrequencyResponse": "20Hz-170Hz",
//         "Price": 2350,
//         "Brand": "XTREME",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Output Power 10W+5W*2 (20 RMS) Power Supply ~230V 50Hz Drive Units Sat : 2.5\" X 2 + Sub : 4\" Frequency Response Sat: 120Hz-20KHz, Sub: >20Hz-170Hz Separation >40dB SIN >70dB Distortion <0.5% (1K, 1W) Dimension Subwoofer Size : W150*H241mm*D237 Satellites Size : W90*H148mm*D86mm",
//         "Category": "Speaker",
//         "ProductId": 4016,
//         "img1": "https://i.ibb.co/vd9Frdx/XTREME-HERO-2-1-SPEAKER-1.png",
//         "img2": "https://i.ibb.co/1Mx5bFd/XTREME-HERO-2-1-SPEAKER-2.png",
//         "AvgRatings": 4.2,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cda",
//         "Model": "Microlab M300U 2.1 Speaker",
//         "InputSensitivity": "3.5ST/USB/SD",
//         "FrequencyResponse": "40 Hz – 20 kHz",
//         "Price": 2650,
//         "Brand": "Microlab",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Quality 2.1 speaker system with built-in amplifier Stylish and compact appearance 38 Watt of acoustic power with 5″ woofer and 2.5″ tweeter driver Full audio spectrum performances, ideal for your Mp3/4 entertainment or other digital music appreciation Built-in FM tuner for FM radio broadcast Coming with instant digital music playback function Volume or playback controls for quick access and adjustment",
//         "Category": "Speaker",
//         "ProductId": 4014,
//         "img1": "https://i.ibb.co/R4gvbrC/Microlab-M300-U-2-1-Speaker-1.png",
//         "img2": "https://i.ibb.co/cNybhWQ/Microlab-M300-U-2-1-Speaker-2.png",
//         "AvgRatings": 4.9,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd4",
//         "Model": "FANTECH BS150 BLUETOOTH LED BASS PORTABLE GAMING SPEAKER (SPACE EDITION)",
//         "InputSensitivity": "Wired / Wireless",
//         "FrequencyResponse": "2KHz-20KHz",
//         "Price": 2200,
//         "Brand": "Fantech",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Type: Bluetooth Speaker Connectivity: Wired / Wireless Illumination: Blue LEDs Core Construction: ABS Weight: 670gr Without Cable Connector Type: Bluetooth, AUX Cable Dimension: 400*58*67mm Cable Material: PVC (AUX Cable) Cable Length:60cm(AUX Cable) Speaker Impedance: 4 Ohm Driver: 45 MM USB: 5 V (3 W + 3 W) Frequency Range : 2KHz-20KHz",
//         "Category": "Speaker",
//         "ProductId": 4008,
//         "img1": "https://i.ibb.co/N3x1Jr3/FANTECH-BS150-BLUETOOTH-LED-BASS-PORTABLE-GAMING-SPEAKER-SPACE-EDITION-1.png",
//         "img2": "https://i.ibb.co/Qf4r2m1/FANTECH-BS150-BLUETOOTH-LED-BASS-PORTABLE-GAMING-SPEAKER-SPACE-EDITION-2.png",
//         "AvgRatings": 4.4,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cde",
//         "Model": "Xtreme E129BU 2:1 Bluetooth Speaker with Remote",
//         "InputSensitivity": "3.5ST/USB/SD",
//         "FrequencyResponse": "20Hz-20KHz",
//         "Price": 2625,
//         "Brand": "XTREME",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "The Xtreme E129BU 2:1 Bluetooth Speaker with Remote is a 2.1CH speaker with 20Hz-20KHz frequency. The Xtreme E129BU Speaker provides an output power of 12W + 8W*2 (RMS) and requires a power supply of AC220V, 50Hz. The speaker has 40dB of separation noise, 70dB of Signal to noise ratio and a distortion percentage of 0.5%. The speaker is packed with features like bluetooth pairing ability, USB port usage, remote control and more. The Xtreme E129BU 2:1 Bluetooth Speaker has 1 Year Warranty.",
//         "Category": "Speaker",
//         "ProductId": 4018,
//         "img1": "https://i.ibb.co/4dzDfdz/Xtreme-E129-BU-2-1-Bluetooth-Speaker-with-Remote-1.png",
//         "img2": "https://i.ibb.co/RP5k03g/Xtreme-E129-BU-2-1-Bluetooth-Speaker-with-Remote-2.png",
//         "AvgRatings": 4.4,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd0",
//         "Model": "Edifier R103V-BT 2.1 Bluetooth Speaker",
//         "InputSensitivity": "3.5mm Stereo Plug Line-In Dual Input",
//         "FrequencyResponse": "70Hz - 20KHz",
//         "Price": 2700,
//         "Brand": "Edifier",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Sensitivity R/L: 350+-50mV, SW: 200+-50mV.Feature: High-quality sound in all speakers, Ideal for laptops or as a multimedia mini speaker system, Laptop Multiple Speaker, The subwoofer uses a 4-inch woofer, The subwoofer is made of vertical cubic design, The medium density fiberboard material that helps keep the woofers still while resonating deep beats.Others INPUT SENSITIVITY: Satellite: 350+-50mV, Subwoofer: 200+-50mV, ADJUSTMENT: Master volume control Channel, SUBWOOFER UNIT: 4 inch (102mm), Magnetically shielded, 6Ω, with bass reflection port, MIDRANGE UNIT: 2.75 inch (73mm), Magnetically shielded, 4Ω.Specialty: The downward firing subwoofer are designed to create a good low-frequency effect, In addition, the woofer also uses a dual magnetic circuit design, ensuring the subwoofer is magnetically shielded protecting monitors and TVs from warping effects",
//         "Category": "Speaker",
//         "ProductId": 4004,
//         "img1": "https://i.ibb.co/8XxJpH9/Edifier-R103-V-BT-2-1-Bluetooth-Speaker-1.png",
//         "img2": "https://i.ibb.co/bKmzQPL/Edifier-X100-B-RMS-Bluetooth-2-1-Multimedia-Speaker-2.png",
//         "AvgRatings": 4.5,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd6",
//         "Model": "Microlab B17 2.0 Stereo USB Speaker",
//         "InputSensitivity": "Wired / Wireless",
//         "FrequencyResponse": "80 Hz – 20 kHz",
//         "Price": 950,
//         "Brand": "Microlab",
//         "Type": "Wired",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Microlab B17 stereo system has a compact size and modern design. The model will look organically next to any personal computer or laptop and will pleasantly surprise you with a clean and balanced sound. Thanks to the arrangement of the function buttons and the headphone jack on the front panel, the system control is quick and comfortable. Volume control with on / off power to the speakers. Housing made of durable and high-quality plastic. The speaker system is compatible with various devices that have a USB port and a standard 3.5 mm stereo connector. Channel separation > 40 dB,Impedance 3 ohm, output power 3 W x 2.",
//         "Category": "Speaker",
//         "ProductId": 4010,
//         "img1": "https://i.ibb.co/GFtSs1f/Microlab-B17-2-0-Stereo-USB-Speaker-1.png",
//         "img2": "https://i.ibb.co/RgB27Ds/Microlab-B17-2-0-Stereo-USB-Speaker-2.png",
//         "AvgRatings": 4.3,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234ccd",
//         "Model": "Edifier R19U 2:0 USB Audio & Power Speaker",
//         "InputSensitivity": "(AUX: 500mV ± 50mV INPUT SENSITIVITY\nUSB: 650mFS ± 50mFS",
//         "FrequencyResponse": "150 Hz- 20kHz (±5db)",
//         "Price": 1600,
//         "Brand": "Edifier",
//         "Type": "Wired",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Edifier R19U USB Audio & Power 2:0 Speaker comes with USB direct power 2.0 speaker system. Which is built in Angled design reduces interference with Large knob controls volume and power. The latest R19U speaker compact powered USB speakers are equipped with Edifier’s latest 2.75 full-range speaker unit, engineered to deliver wide and detailed sound with just two speakers. This Speaker is completed with the pearl-white, bullet-shaped design, this 2.0 desktop speaker system offers both style and sound quality at an amazing value. This speakers also has a balanced and very clear sound with no distortion or interruption to quality. Being powered by a USB is a plus and a convenience not afforded too many.",
//         "Category": "Speaker",
//         "ProductId": 4001,
//         "img1": "https://i.ibb.co/KjwX5pf/Edifier-R19-U-2-0-USB-Audio-Power-Speaker-1.png",
//         "img2": "https://i.ibb.co/1msWYfS/Edifier-R19-U-2-0-USB-Audio-Power-Speaker-2.png",
//         "AvgRatings": 3.4,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234ccf",
//         "Model": "Edifier X100B RMS Bluetooth 2:1 Multimedia Speaker",
//         "InputSensitivity": "500mV ± 50mV,",
//         "FrequencyResponse": "150 Hz - 20 KHz",
//         "Price": 2500,
//         "Brand": "Edifier",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "X100B gives you a sensational audio experience with deep bass, intense, and balanced treble, preserving the sharpness of every detail and staying away from distortions even when highly demanded. A non-resonant Meddite MDF construction, with extra bracing and minimum thick baffles, ensures a more lifelike sound which revolutionize your gamers, movies, and music with the X100B and listen to superior quality.",
//         "Category": "Speaker",
//         "ProductId": 4003,
//         "img1": "https://i.ibb.co/8mxfF0m/Edifier-X100-B-RMS-Bluetooth-2-1-Multimedia-Speaker-1.png",
//         "img2": "https://i.ibb.co/9yW8t7k/Edifier-R103-V-BT-2-1-Bluetooth-Speaker-2.png",
//         "AvgRatings": 4.5,
//         "Status": "Out of Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cd3",
//         "Model": "Fantech Rumble GS204 USB RGB Speaker",
//         "InputSensitivity": "USB + 3.5mm TRRS jack",
//         "FrequencyResponse": "130-20,000Hz",
//         "Price": 2400,
//         "Brand": "Fantech",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "Clear, Deep, and Perfect Sound 360° surround sound Hi-res audio 45mm driver unit Lighting effects Magnet free material body Multi-platform compatibility (Laptop, Desktop, Cellphone) USB& 3.5mm plug Dimensions: 100mm*80mm",
//         "Category": "Speaker",
//         "ProductId": 4007,
//         "img1": "https://i.ibb.co/qB66Qbm/Fantech-Rumble-GS204-USB-RGB-Speaker-1.png",
//         "img2": "https://i.ibb.co/hFhPJ30/Fantech-Rumble-GS204-USB-RGB-Speaker-2.png",
//         "AvgRatings": 5,
//         "Status": "Out of Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       },
//       {
//         "_id": "64f0208a1e3a647be4234cdb",
//         "Model": "XTREME E121 Multimedia Speaker 2:1",
//         "InputSensitivity": "3.5ST/USB/SD",
//         "FrequencyResponse": "20Hz-20KHz, Sub: >20Hz-170Hz",
//         "Price": 1975,
//         "Brand": "XTREME",
//         "Type": "Multimedia",
//         "SystemRequirements": "Windows 10 and Mac OSX 10.12 Sierra.",
//         "Details": "The XTREME E121 Speakers from XTREME are designed to deliver stellar-quality audio for your computer, TV, or gaming system. Each speaker features two dual-woven optical fiber drivers also as a silk dome tweeter. As such, the XTREME E121 speakers deliver crystal clear highs also as full-range audio. additionally, the XTREME E121 speakers feature built-in 2:1 Multimedia speakers to deliver rich, exceptional bass without the necessity for a subwoofer. The frequency range for the XTREME E121 speakers is 20Hz to 20kHz.",
//         "Category": "Speaker",
//         "ProductId": 4015,
//         "img1": "https://i.ibb.co/F7bzx20/XTREME-E121-Multimedia-Speaker-2-1-1.png",
//         "img2": "https://i.ibb.co/jVtyj5Y/XTREME-E121-Multimedia-Speaker-2-1-2.png",
//         "AvgRatings": 3.3,
//         "Status": "In Stock",
//         "Reviews": [
//           "The soundbox I selected provides rich and immersive audio, enhancing my entertainment experience. However, it could benefit from more advanced equalization settings.",
//           "I'm quite satisfied with my soundbox's performance, as it delivers clear and powerful sound. Still, it lacks Bluetooth connectivity, which limits its versatility.",
//           "My chosen soundbox has proven itself to be a dependable choice, with crisp audio and ample volume. However, it could have more input options for various devices.",
//           "The soundbox has performed well, offering excellent sound quality for music and movies. However, it may not be the most space-saving option due to its size."
//         ]
//       }
//     ],
//     "totalProducts": 240
//   }