import mongoose from "mongoose";

const pcBuilderSchema = new mongoose.Schema(
  {
    email: {
      type: String,
      required: true,
      unique: true,
      index: true,
    },
    Speaker: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    UPS: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    RAM: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    ROM: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    SSD: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    PSU: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    GPU: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    Mouse: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    MotherBoard: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    Monitor: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    Keyboard: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    CPU: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    CpuCooler: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
    Casing: {
      _id: mongoose.Schema.Types.ObjectId,
      Brand: String,
      Category: String,
      Model: String,
      img1: String,
      Details: String,
      Price: Number,
      ProductId: Number,
    },
  },
  {
    timestamps: true,
  }
);

export const PCBuilder = mongoose.model("PCBuilder", pcBuilderSchema);
